# Generated by Django 5.2.8 on 2025-11-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(unique=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, null=True)),
                ('has_pc', models.GeneratedField(db_persist=False, expression=models.Case(models.When(ip_address__isnull=False, then=True), default=False), output_field=models.BooleanField())),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
